openapi: 3.1.0
info:
  title: GPTCalendar API
  description: API for managing events in Google Calendar
  version: "1.0"

servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a new calendar event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventInput"
      responses:
        "200":
          description: Successful creation

  /update_event:
    post:
      summary: Update an existing event
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateInput"
      responses:
        "200":
          description: Successful update

  /delete_event:
    post:
      summary: Delete a calendar event
      operationId: deleteEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
      responses:
        "200":
          description: Successful deletion

  /query_events:
    get:
      summary: Get events in a date range
      operationId: queryEvents
      parameters:
        - name: start
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: List of events

  /analyze_events:
    post:
      summary: Analyze events for trends
      operationId: analyzeEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnalysisInput"
      responses:
        "200":
          description: Analysis result

components:
  schemas:
    EventInput:
      type: object
      required:
        - summary
        - start
        - end
        - user_timezone
      properties:
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string
        recurrence:
          type: string

    UpdateInput:
      type: object
      required:
        - event_id
      properties:
        event_id:
          type: string
        summary:
          type: string
        description:
          type: string
        start:
          type: string
        end:
          type: string
        user_timezone:
          type: string

    AnalysisInput:
      type: object
      required:
        - analysis_type
        - date_range
      properties:
        analysis_type:
          type: string
          enum:
            - busiest_day
            - emptiest_day
            - most_common_event
            - event_count
            - event_list
            - summary
        date_range:
          type: object
          required:
            - start
            - end
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
        filter_keywords:
          type: array
          items:
            type: string
