openapi: 3.1.0
info:
  title: GPT Calendar Plugin
  description: API for managing Google Calendar events with full reminder support
  version: "1.0.0"
servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a new event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - summary
                - start
                - end
              properties:
                summary:
                  type: string
                  description: Event title
                description:
                  type: string
                  description: Event description
                location:
                  type: string
                  description: Event location
                start:
                  type: object
                  required:
                    - dateTime
                    - timeZone
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: Start date and time in ISO format
                    timeZone:
                      type: string
                      description: Time zone (e.g., Australia/Sydney)
                end:
                  type: object
                  required:
                    - dateTime
                    - timeZone
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: End date and time in ISO format
                    timeZone:
                      type: string
                      description: Time zone (e.g., Australia/Sydney)
                recurrence:
                  type: array
                  items:
                    type: string
                  description: Recurrence rules (RRULE format)
                reminders:
                  type: object
                  description: Event reminder settings
                  properties:
                    useDefault:
                      type: boolean
                      description: Whether to use default reminders
                    overrides:
                      type: array
                      description: Custom reminder overrides
                      items:
                        type: object
                        required:
                          - method
                          - minutes
                        properties:
                          method:
                            type: string
                            enum: ["popup", "email"]
                            description: Reminder method
                          minutes:
                            type: integer
                            description: Minutes before event to remind
      responses:
        "200":
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  event_id:
                    type: string

  /update_event:
    post:
      summary: Update an existing event
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventId
              properties:
                eventId:
                  type: string
                  description: The ID of the event to update
                summary:
                  type: string
                  description: Event title
                description:
                  type: string
                  description: Event description
                location:
                  type: string
                  description: Event location
                start:
                  type: object
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: Start date and time in ISO format
                    timeZone:
                      type: string
                      description: Time zone (e.g., Australia/Sydney)
                end:
                  type: object
                  properties:
                    dateTime:
                      type: string
                      format: date-time
                      description: End date and time in ISO format
                    timeZone:
                      type: string
                      description: Time zone (e.g., Australia/Sydney)
                recurrence:
                  type: array
                  items:
                    type: string
                  description: Recurrence rules (RRULE format)
                reminders:
                  type: object
                  description: Event reminder settings
                  properties:
                    useDefault:
                      type: boolean
                      description: Whether to use default reminders
                    overrides:
                      type: array
                      description: Custom reminder overrides
                      items:
                        type: object
                        required:
                          - method
                          - minutes
                        properties:
                          method:
                            type: string
                            enum: ["popup", "email"]
                            description: Reminder method
                          minutes:
                            type: integer
                            description: Minutes before event to remind
      responses:
        "200":
          description: Event updated successfully

  /delete_event:
    post:
      summary: Delete an event
      operationId: deleteEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventId
              properties:
                eventId:
                  type: string
                  description: The ID of the event to delete
      responses:
        "200":
          description: Event deleted successfully

  /query_events:
    post:
      summary: Query events in a time range
      operationId: queryEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start
                - end
              properties:
                start:
                  type: string
                  format: date
                  description: Start date in YYYY-MM-DD format
                end:
                  type: string
                  format: date
                  description: End date in YYYY-MM-DD format
      responses:
        "200":
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: Calendar event object
