openapi: 3.1.0
info:
  title: GPT Calendar Plugin
  description: API for managing Google Calendar events and analyzing schedules.
  version: "1.0.0"
servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a new calendar event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventInput"
      responses:
        "200":
          description: Successful creation

  /update_event:
    post:
      summary: Update an existing event
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEventInput"
      responses:
        "200":
          description: Successful update

  /delete_event:
    post:
      summary: Delete a calendar event
      operationId: deleteEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
              required:
                - event_id
      responses:
        "200":
          description: Successful deletion

  /query_events:
    get:
      summary: Get events in a date range
      operationId: queryEvents
      parameters:
        - in: query
          name: start
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: List of events

  /analyze_events:
    post:
      summary: Analyze calendar events
      operationId: analyzeEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                analysis_type:
                  type: string
                  enum:
                    - busiest_day
                    - emptiest_day
                    - most_common_event
                    - event_count
                    - event_list
                    - summary
                date_range:
                  type: object
                  properties:
                    start:
                      type: string
                      format: date
                    end:
                      type: string
                      format: date
                  required:
                    - start
                    - end
                filter_keywords:
                  type: array
                  items:
                    type: string
              required:
                - analysis_type
                - date_range
      responses:
        "200":
          description: Analysis results

components:
  schemas:
    EventInput:
      type: object
      properties:
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string
        recurrence:
          type: string
      required:
        - summary
        - start
        - end
        - user_timezone

    UpdateEventInput:
      type: object
      properties:
        event_id:
          type: string
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string
      required:
        - event_id
