openapi: 3.1.0
info:
  title: GPT Calendar
  description: A personal calendar assistant that helps manage your schedule using natural language. It supports event creation, updates, deletions, queries, and analytics.
  version: "1.0.0"

servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      operationId: createEvent
      summary: Create a calendar event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /update_event:
    post:
      operationId: updateEvent
      summary: Update an existing calendar event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInput'
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /delete_event:
    post:
      operationId: deleteEvent
      summary: Delete a calendar event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [event_id]
              properties:
                event_id:
                  type: string
      responses:
        '200':
          description: Event deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /query_events:
    get:
      operationId: queryEvents
      summary: Get calendar events within a time range
      parameters:
        - name: start
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object

  /analyze_events:
    post:
      operationId: analyzeEvents
      summary: Analyze event trends and statistics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeInput'
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    EventInput:
      type: object
      required:
        - summary
        - start
        - end
      properties:
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string
        recurrence:
          type: string

    UpdateInput:
      type: object
      required:
        - event_id
      properties:
        event_id:
          type: string
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string

    AnalyzeInput:
      type: object
      required:
        - analysis_type
        - date_range
      properties:
        analysis_type:
          type: string
          enum:
            - busiest_day
            - emptiest_day
            - most_common_event
            - event_count
            - event_list
            - summary
        date_range:
          type: object
          required: [start, end]
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
        filter_keywords:
          type: array
          items:
            type: string

    SuccessResponse:
      type: object
      properties:
        status:
          type: string
        event_id:
          type: string
