openapi: 3.1.0
info:
  title: GPT Calendar Plugin
  description: API for managing Google Calendar events with full reminder support
  version: "1.0.0"
servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a new event
      operationId: createEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - summary
                - start
                - end
              properties:
                summary:
                  type: string
                description:
                  type: string
                location:
                  type: string
                start:
                  type: object
                end:
                  type: object
                recurrence:
                  type: array
                  items:
                    type: string
                reminders:
                  type: object
      responses:
        '200':
          description: Event created

  /update_event:
    post:
      summary: Update an existing event
      operationId: updateEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventId
              properties:
                eventId:
                  type: string
                summary:
                  type: string
                description:
                  type: string
                location:
                  type: string
                start:
                  type: object
                end:
                  type: object
                recurrence:
                  type: array
                  items:
                    type: string
                reminders:
                  type: object
      responses:
        '200':
          description: Event updated

  /delete_event:
    post:
      summary: Delete an event
      operationId: deleteEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventId
              properties:
                eventId:
                  type: string
      responses:
        '200':
          description: Event deleted

  /query_event:
    post:
      summary: Query events by time range
      operationId: queryEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - start
                - end
              properties:
                start:
                  type: string
                end:
                  type: string
      responses:
        '200':
          description: Events returned

components:
  schemas: {}   # ✅ 必須至少是一個空 object
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            calendar: Access Google Calendar events
