openapi: 3.1.0
info:
  title: GPT Calendar Plugin
  description: API for managing Google Calendar events with full reminder support
  version: "1.0.0"
servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a new event
      operationId: createEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "created"
                  event_id:
                    type: string
                    example: "abc123xyz"

  /update_event:
    post:
      summary: Update an existing event
      operationId: updateEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "updated"
                  event_id:
                    type: string

  /delete_event:
    post:
      summary: Delete an event
      operationId: deleteEvent
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteEventRequest'
      responses:
        '200':
          description: Event deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "deleted"

  /query_events:
    post:
      summary: Query events by time range
      operationId: queryEvents
      security:
        - OAuth2: [calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryEventsRequest'
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventResponse'

components:
  schemas:
    CreateEventRequest:
      type: object
      required:
        - summary
        - start
        - end
      properties:
        summary:
          type: string
          description: Event title
          example: "Lunch with Sarah"
        description:
          type: string
          description: Event description
          example: "Catching up"
        location:
          type: string
          description: Event location
          example: "Downtown Cafe"
        start:
          $ref: '#/components/schemas/EventDateTime'
        end:
          $ref: '#/components/schemas/EventDateTime'
        recurrence:
          type: array
          items:
            type: string
          example: ["RRULE:FREQ=WEEKLY;BYDAY=FR"]
        reminders:
          $ref: '#/components/schemas/EventReminders'

    UpdateEventRequest:
      type: object
      required:
        - eventId
      properties:
        eventId:
          type: string
          description: The ID of the event to update
          example: "abc123xyz"
        summary:
          type: string
          example: "Updated meeting title"
        description:
          type: string
        location:
          type: string
        start:
          $ref: '#/components/schemas/EventDateTime'
        end:
          $ref: '#/components/schemas/EventDateTime'
        recurrence:
          type: array
          items:
            type: string
        reminders:
          $ref: '#/components/schemas/EventReminders'

    DeleteEventRequest:
      type: object
      required:
        - eventId
      properties:
        eventId:
          type: string
          description: The ID of the event to delete
          example: "abc123xyz"

    QueryEventsRequest:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: string
          format: date
          description: Start date in YYYY-MM-DD format
          example: "2025-07-31"
        end:
          type: string
          format: date
          description: End date in YYYY-MM-DD format
          example: "2025-08-07"

    EventDateTime:
      type: object
      required:
        - dateTime
        - timeZone
      properties:
        dateTime:
          type: string
          format: date-time
          description: Date and time in ISO format (without timezone suffix)
          example: "2025-07-26T12:00:00"
        timeZone:
          type: string
          description: Timezone identifier
          example: "Australia/Sydney"

    EventReminders:
      type: object
      properties:
        useDefault:
          type: boolean
          description: Whether to use default reminders
          example: false
        overrides:
          type: array
          items:
            $ref: '#/components/schemas/ReminderOverride'

    ReminderOverride:
      type: object
      required:
        - method
        - minutes
      properties:
        method:
          type: string
          enum: ["popup", "email"]
          description: Reminder method
          example: "popup"
        minutes:
          type: integer
          description: Minutes before event to remind
          example: 10

    EventResponse:
      type: object
      properties:
        summary:
          type: string
          example: "Meeting with team"
        start:
          $ref: '#/components/schemas/EventDateTime'
        end:
          $ref: '#/components/schemas/EventDateTime'
        eventId:
          type: string
          example: "abc123xyz"

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            calendar: Access Google Calendar events
