openapi: 3.1.0
info:
  title: GPT Calendar API
  description: A plugin that allows ChatGPT to create, query, update, delete, and analyze Google Calendar events.
  version: "1.0.0"
servers:
  - url: https://gptcalendar.onrender.com

paths:
  /create_event:
    post:
      summary: Create a calendar event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '200':
          description: Event successfully created

  /update_event:
    post:
      summary: Update a calendar event
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventUpdate'
      responses:
        '200':
          description: Event successfully updated

  /delete_event:
    post:
      summary: Delete a calendar event
      operationId: deleteEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
      responses:
        '200':
          description: Event successfully deleted

  /query_events:
    get:
      summary: Query calendar events within a date range
      operationId: queryEvents
      parameters:
        - name: start
          in: query
          required: true
          schema:
            type: string
            example: "2025-07-24"
        - name: end
          in: query
          required: true
          schema:
            type: string
            example: "2025-07-26"
      responses:
        '200':
          description: Events retrieved successfully

  /analyze_events:
    post:
      summary: Analyze calendar events
      operationId: analyzeEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisInput'
      responses:
        '200':
          description: Analysis result returned

components:
  schemas:
    EventInput:
      type: object
      required: [summary, start, end, user_timezone]
      properties:
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string
        recurrence:
          type: string

    EventUpdate:
      type: object
      required: [event_id]
      properties:
        event_id:
          type: string
        summary:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        user_timezone:
          type: string

    AnalysisInput:
      type: object
      required: [analysis_type, date_range]
      properties:
        analysis_type:
          type: string
          enum: [event_count, event_list, busiest_day, emptiest_day, most_common_event, summary]
        date_range:
          type: object
          properties:
            start:
              type: string
              example: "2025-07-24"
            end:
              type: string
              example: "2025-07-30"
        filter_keywords:
          type: array
          items:
            type: string
