openapi: 3.1.0
servers:
  - url: https://gptcalendar.onrender.com
info:
  title: ReminderGPT Calendar API
  description: API for creating reminders using Google Calendar
  version: "1.0"
paths:
  /create_reminder:
    post:
      summary: Create a new calendar event
      operationId: createReminder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
                start:
                  type: string
                end:
                  type: string
      responses:
        '200':
          description: Event created successfully
